### ISSUE TITLE
Ресёрч `NAudio`

### ISSUE THREAD

**Issue by JabaJabila** [is-tech-y24-1/Do-Svyazi.Music#51]
Пришло время заняться реальной музыкой и проресёрчить вопрос с библиотекой [`NAudio`](https://github.com/naudio/NAudio). Главное - понять, как стримить музыку юзерам, и поделиться инфой с командой

**Comment by Ssspook** [comment]
По результатам исследований пришёл к выводу, что стриминг в живом времени не получится, ибо все либы для этого работают только под винду, а кросплатформенные решения оставляют желать лучшего. А также у нас скоро защита и мы не можем себе позволить заебаться с этим надолго, ибо у нас ещё много чего надо сделать.

Итог: будем сохранять музыку в кэш и проигрывать оттуда аки телеграм.
